lab=5-humongous
profile=humongous-allocations
jvm.options=-Xms1g -Xmx1g -XX:+UseG1GC
simulation=net.safedata.performance.training.lab.simulations.HumongousSimulation
stats.path=/lab/humongous/stats
log.counter.humongousGcEvents=gc.log:G1 Humongous Allocation
threshold.count.humongousGcEvents=1
