lab=2-nplus1
profile=n-plus-one-queries
jvm.options=-Xms512m -Xmx512m -XX:+UseG1GC
simulation=net.safedata.performance.training.lab.simulations.NPlusOneSimulation
stats.path=/lab/nplus1/stats
threshold.count.sqlStatementsPerRequest=3
