lab=1-retention
profile=unbounded-retention
jvm.options=-Xms256m -Xmx256m -XX:+UseG1GC
simulation=net.safedata.performance.training.lab.simulations.RetentionSimulation
stats.path=/lab/retention/stats
threshold.count.retainedQuotes=1000
